### ISSUE TITLE
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: 'ld'

### ISSUE THREAD

**Issue by lokicherry** [upsidetravel/bucket-antivirus-function#113]
Getting this issue when I am running this in a lambda function. 
[ERROR] FileNotFoundError: [Errno 2] No such file or directory: 'ld'
Traceback (most recent call last):
  File "/var/task/update.py", line 44, in lambda_handler
    clamav.update_defs_from_freshclam(AV_DEFINITION_PATH, CLAMAVLIB_PATH)
  File "/var/task/clamav.py", line 115, in update_defs_from_freshclam
    ":".join(current_library_search_path()),
  File "/var/task/clamav.py", line 45, in current_library_search_path
    ld_verbose = subprocess.check_output(["ld", "--verbose"]).decode("utf-8")
  File "/var/lang/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/var/lang/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/var/lang/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/var/lang/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)END RequestId: e2d4e70b-35a4-4ee5-b81e-881b89f16b76
REPORT RequestId: e2d4e70b-35a4-4ee5-b81e-881b89f16b76	Duration: 2082.57 ms	Billed Duration: 2100 ms	Memory Size: 128 MB	Max Memory Used: 82 MB	Init Duration: 265.13 ms

**Comment by lokicherry** [comment]
This issue is coming in python 3.8 runtime.

**Comment by mkuait10** [comment]
Even i have started facing the issue. Any resolution yet ?

**Comment by hirohirox** [comment]
When I run it with python 3.9, the same thing happens. but when I run it in python 3.7 it doesn't happen.

**Comment by mkuait10** [comment]
The reason is that python 3.7  and python 3.8/3.9 Lambda runtime env are using different underlying docker image. Hence it works in 3.7 whereas id does not work in 3.8/3.9.

If you want to use python3.8/3.9, then use your own docker image to upload Lambda.

**Comment by jeff1evesque** [comment]
Install `ld` within the `Dockerfile` (via `yum install `binutils`), and copy it to the `bin/` directory.  Next, adjust the provided `updated.py`:

```python
def current_library_search_path():
    ld_verbose = subprocess.check_output(["./bin/ld", "--verbose"]).decode("utf-8")
    rd_ld = re.compile(RE_SEARCH_DIR)
    return rd_ld.findall(ld_verbose)
```

You'll discover you need to manually copy additional `xxx.so` files into the `bin/` directory, in the same `Dockerfile`.

**Comment by jeff1evesque** [comment]
Install `ld` within the `Dockerfile` (via `yum install binutils`), and copy it to the `bin/` directory.  Next, adjust the provided `updated.py`:

```python
def current_library_search_path():
    ld_verbose = subprocess.check_output(["./bin/ld", "--verbose"]).decode("utf-8")
    rd_ld = re.compile(RE_SEARCH_DIR)
    return rd_ld.findall(ld_verbose)
```

You'll discover you need to manually copy additional `xxx.so` files into the `bin/` directory, in the same `Dockerfile`.

**Comment by jeff1evesque** [comment]
Install `ld` within the `Dockerfile` (via `yum install binutils`), and copy it to the `bin/` directory.  Next, adjust the provided `clamav.py`:

```python
def current_library_search_path():
    ld_verbose = subprocess.check_output(["./bin/ld", "--verbose"]).decode("utf-8")
    rd_ld = re.compile(RE_SEARCH_DIR)
    return rd_ld.findall(ld_verbose)
```

You'll discover you need to manually copy additional `xxx.so` files into the `bin/` directory, in the same `Dockerfile`.

**Comment by jeff1evesque** [comment]
I confirmed that when using python 3.7, the `clamav.py` did not display any error.  Overall, making simple adjustments, or moderate adjustments to corresponding build processes (if that's what you have) is much worth the time, then going down rabbit holes of missing `xxx.so` files on the python 3.8 environment.

**Comment by gonovanatasha** [comment]
ld works on python3.8 python3.9? @jeff1evesque 
Id works can you share copy command for bin/ld
