### ISSUE TITLE
[ERROR] NotADirectoryError: [Errno 20] Not a directory: for a file with random name '.2e4Ee1BA' (changes each time)

### ISSUE THREAD

**Issue by Muthuveerappanv** [upsidetravel/bucket-antivirus-function#120]
[ERROR] NotADirectoryError: [Errno 20] Not a directory: '/tmp/test/aa9d4608-ee3a-4b5c-8337-1d2bef57fe5e/**.2e4Ee1BA'** -> '/tmp/test/aa9d4608-ee3a-4b5c-8337-1d2bef57fe5e/'
Traceback (most recent call last):
  File "/var/task/scan.py", line 241, in lambda_handler
    s3_object.download_file(file_path)
  File "/var/runtime/boto3/s3/inject.py", line 314, in object_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/var/runtime/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/var/runtime/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/var/runtime/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/var/runtime/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/var/runtime/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/var/runtime/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/var/runtime/s3transfer/download.py", line 601, in _main
    osutil.rename_file(fileobj.name, final_filename)
  File "/var/runtime/s3transfer/utils.py", line 273, in rename_file
    rename_file(current_filename, new_filename)

**Comment by rahulvinodsharma** [comment]
Is there any solution for this?
