### ISSUE TITLE
[ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff

### ISSUE THREAD

**Issue by nqdrizzt** [upsidetravel/bucket-antivirus-function#183]
Hello,
I have the latest verson of the project running in AWS to scan a bucket.
After uploading a binary exe file, in this case 7z1900-x64.exe ( 7z portable installer) the following error is thrown by the clamav scanner:

`
[ERROR] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 6831: invalid start byte
Traceback (most recent call last):
File "/var/task/scan.py", line 238, in lambda_handler
  scan_result, scan_signature = clamav.scan_file(file_path)
File "/var/task/clamav.py", line 197, in scan_file
  output = av_proc.communicate()[0].decode()
`
Is there a way to fix this ?

**Comment by tianbiao** [comment]
Hi @nqdrizzt I met the same issue and there is a workaround from my team member is to remove the `-a` from below code 

`av_proc = subprocess.Popen(
        [CLAMSCAN_PATH, "-v", "-a", "--stdout", "-d", AV_DEFINITION_PATH, path],
        stderr=subprocess.STDOUT,
        stdout=subprocess.PIPE,
        env=av_env,
    )`
