### ISSUE TITLE
AV_DELETE_INFECTED_FILES does not delete files

### ISSUE THREAD

**Issue by richrawlings** [upsidetravel/bucket-antivirus-function#192]
Enabling the `AV_DELETE_INFECTED_FILES` setting results in this:

```
[ERROR] Exception: Failed to delete infected file: av-files.test-infected.zip
Traceback (most recent call last):
  File "/var/task/scan.py", line 270, in lambda_handler
    delete_s3_object(s3_object)
  File "/var/task/scan.py", line 113, in delete_s3_object
    % (s3_object.bucket_name, s3_object.key)
```

The exception message doesn't give much away. Is this likely to be a permissions / policy issue?

**Comment by richrawlings** [comment]
Was a simple policy issue.
