### ISSUE TITLE
Error when testing with Eicar file 

### ISSUE THREAD

**Issue by BabuBasha** [upsidetravel/bucket-antivirus-function#73]
I am getting the below error when i run a test for the infected file using eicar antivirus test file.
 Any help would be much appreciated. 
Errror trace: 
An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/scan.py", line 160, in lambda_handler
sns_scan_results(s3_object, scan_result)
File "/var/task/scan.py", line 128, in sns_scan_results
"version": s3_object.version_id,
File "/var/runtime/boto3/resources/factory.py", line 339, in property_loader
self.load()
File "/var/runtime/boto3/resources/factory.py", line 505, in do_action
response = action(self, *args, **kwargs)
File "/var/runtime/boto3/resources/action.py", line 83, in __call__
response = getattr(parent.meta.client, operation_name)(**params)
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by BabuBasha** [comment]
I found this error as well. 
An error occurred (403) when calling the HeadObject operation: Forbidden: ClientError
Traceback (most recent call last):
File "/var/task/scan.py", line 153, in lambda_handler
file_path = download_s3_object(s3_object, "/tmp")
File "/var/task/scan.py", line 62, in download_s3_object
s3_object.download_file(local_path)
File "/var/runtime/boto3/s3/inject.py", line 314, in object_download_file
ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
File "/var/runtime/boto3/s3/inject.py", line 172, in download_file
extra_args=ExtraArgs, callback=Callback)
File "/var/runtime/boto3/s3/transfer.py", line 307, in download_file
future.result()
File "/var/runtime/s3transfer/futures.py", line 73, in result
return self._coordinator.result()
File "/var/runtime/s3transfer/futures.py", line 233, in result
raise self._exception
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by BabuBasha** [comment]
Just an update, the role has full access to s3 bucket..

**Comment by BabuBasha** [comment]
Sorry.. There was a bucket policy created by my team mate that was giving the error. Removed the policy and works like a charm.

**Comment by anuj9196** [comment]
@BabuBasha What was the bucket policy you removed to fix it. I'm also getting the same error.

**Comment by BabuBasha** [comment]
Hello @anuj9196 , there was a policy not to allow delete  on the files within the bucket where as the lambda deletes the infected files after scan which is why i was getting the error. I removed the policy and it deleted the infected files after scan. Hope this helps..

**Comment by anuj9196** [comment]
@BabuBasha in my case, the issue was related to getting the object version_id while sending SNS in case of denied GetObject on the INFECTED tagged object.

I had to remove `s3_object.version_id` from the SNS notification payload
