### ISSUE TITLE
Invalid parameter: TargetArn: InvalidParameterException for SNS status

### ISSUE THREAD

**Issue by maxpeterson** [upsidetravel/bucket-antivirus-function#99]
I have created a an SNS topic and set the `AV_STATUS_SNS_ARN` to the ARN of the topic. When the `bucket-antivirus-function` lambda function runs it fails with an `InvalidParameterException`, seemingly with the `TargetArn` value.

On inspecting [the code](https://github.com/upsidetravel/bucket-antivirus-function/blob/master/scan.py#L188) I noticed that the `AV_STATUS_SNS_ARN` is passed to `sns_client.publish` as the `TargetArn` value (rather than the `TopicArn`). Could this be the problem? ... And if so 

1. What should the `AV_STATUS_SNS_ARN` be set to?
2. How can I use an SNS topic (so I can manage subscriptions to the notifications)?

> An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: TargetArn: InvalidParameterException
> Traceback (most recent call last):
>   File "/var/task/scan.py", line 256, in lambda_handler
>     result_time,
>   File "/var/task/scan.py", line 195, in sns_scan_results
>     "StringValue": scan_signature,
>   File "/var/runtime/botocore/client.py", line 357, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/var/runtime/botocore/client.py", line 661, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> InvalidParameterException: An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: TargetArn

**Comment by maxpeterson** [comment]
After some more digging I discovered [a stackoverflow article](https://stackoverflow.com/a/21893926/604418) suggesting that the issue may be that my Lambda function and SNS topic are not in the same region.

Changing the region of the topic lead to a more useful permission based error that I was able to resolve!

> An error occurred (AuthorizationError) when calling the Publish operation: User: arn:aws:sts::<account>:assumed-role/bucket-antivirus-function/bucket-antivirus-function is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:<account>:clamav-antivirus-scan-status: AuthorizationErrorException
> Traceback (most recent call last):
>   File "/var/task/scan.py", line 256, in lambda_handler
>     result_time,
>   File "/var/task/scan.py", line 195, in sns_scan_results
>     "StringValue": scan_signature,
>   File "/var/runtime/botocore/client.py", line 357, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/var/runtime/botocore/client.py", line 661, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> AuthorizationErrorException: An error occurred (AuthorizationError) when calling the Publish operation: User: arn:aws:sts::<account>:assumed-role/bucket-antivirus-function/bucket-antivirus-function is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:<account>:clamav-antivirus-scan-status
